### ISSUE TITLE
이 유즈케이스 클래스는 단일 책임 원칙을 위반하는건가요?

### ISSUE THREAD

**Issue by rscarrera27** [EntryDSM/Hermes#9]
현재 Admin에 대한 use case 관련 코드가 AdminService 라는 클래스에 다 들어있습니다.

대략 이런 형식인데요,
```python
class AdminService:

    repository: Repository

    def create(...):
        self.repository.save(...)

    def patch(...):
        self.repository.patch(...)

    def delete(...):
        self.repository.delete(...)

    def get_one(...):
        return self.repository.get(...)[0]

    def get_list(...):
        return self.repository.save(...)
```
원래는 Admin이 하나의 책임이라고 생각해서 이렇게 짰는데 SRP에 대해서 곰곰히 생각해보니까 아닌것같기도 한데

이 클래스를 AdminCreateService, AdminUpdateService 이런 식으로 분할 해야할까요?

**Comment by syeutyu** [comment]
결국 현재 말한 문제가 AdminService라는 service 클래스 하나에 너무 역할이 들어가서 그런건데 아래 폴더 구조같이

/admin
 -- index
 -- finder
 -- helper
 -- etc...

등등의 서비스로 나누면 역할이 각 클래스의 역할이랑 테스트코드가 확실해지지 않을까요
@NovemberOscar

**Comment by rscarrera27** [comment]
> 결국 현재 말한 문제가 AdminService라는 service 클래스 하나에 너무 역할이 들어가서 그런건데 아래 폴더 구조같이
> 
> /admin
> -- index
> -- finder
> -- helper
> -- etc...
> 
> 등등의 서비스로 나누면 역할이 각 클래스의 역할이랑 테스트코드가 확실해지지 않을까요

일단 결국 SRP를 위반하는것같다 이거죠? 근데 이 서비스는 이렇다할 비즈니스 로직이 없고 CRUD만 있는 꼴인데 
이 [스택오버플로우 답변들](https://stackoverflow.com/questions/47871647/classes-with-crud-methods-violating-single-responsibility-principle)을 보면 
> (대충 제가만든 AdminService 처럼 생긴 어떤 클래스) 클래스가 변경되는 유일한 이유는 그 목적, 즉 이 경우 실체를 유지하거나 검색하는 것과 관련이 있어야 한다.

라고 하면서 SRP를 만족한다는것같은데... 

@syeutyu

**Comment by engolder** [comment]
레포지토리를 사용해 데이터를 운반한다는 하나의 목적으로 보입니다

**Comment by syeutyu** [comment]
결국 SRP라는 의미는 클래스는 하나의 목적을 가진 클래스여야 된다는 말입니다

지금 AdminService에서 모델의 어느부분까지 담당하는지는 잘모르겠는데 예시를 들기위해 model의 property와 CRUD를 담당한다고 생각해보고 예시를 들어보면

srp는 변경하려는 단 하나 이유만을 가져야 한다고 결론 짓습니다

현재 설정한 admin service에서 crud를 담당한다면 변경이 가능한 경우의수는 다음과 같습니다
1. 모델의 생성
2. 모델의 삭제
3. 업데이트
4. property수정 및 update
... etc

그렇다면 하나의 변경이유를 가지려면?
간단히 경우의 수에 따라서 각 클래스가 담당하는 역할을 분리하면 된다고 생각합니다

그래서 각 역할을 담당하는 admin 구조안에 각 역할을 담당하는 클래스를 분리하는 구조를 생각했던거구요
이를 통해서 테스트 코드를 작성할때 어느 클래서는 어떤 역할의 테스트만 담당하고 실제 어플리케이션 레이어에서 사용하는 코드를 봤을때도 한번에 확인할수있고요

물론 간단한 crud라면 하나의 model에서 처리를 해도 상관은 없다고 생각합니다

결국 모든 코딩스타일은 말 그대로 스타일일뿐 절대 강조가 아니니 말이죠

코드를 작성하시는 @NovemberOscar 분과 팀원 분들과의 적절한 타협점을 봐서 해결하는게 좋다고 봅니다

**Comment by HubCodes** [comment]
무슨 의미를 가지는 코드인지는 잘 모르겠는데, 단일 책임 원칙이 '하나의 책임' 이라고만 하면 진척이 안 되는 상황에 빠지기 쉽습니다.
다시 말해서 현재 저 클래스가 가져야 하는 추상화 수준이 어떤 정도인지 살펴보라는 얘기입니다.

**책임을 잘게 쪼갠다는 건 추상화 수준 역시 낮추는 작업이라고 생각합니다.**

**Comment by CHANMYUNG** [comment]
단일책임원칙: `클래스를 변경하는 이유가 단 한 가지여야 함`

AdminService: Admin 객체의 생성/수정/삭제를 관리하는 역할.

AdminService 클래스는 Admin객체에 대한 추가요구사항이 있을 때만 변경됨.

`만약` AdminService에서 다른 모델에 대한 처리까지 하게되면 해당 모델에 대한 추가요구사항이 생겼을때도 클래스를 변경하게됨 (이때부터 2가지 이상이 되는것)

SRP를 위반하고있진 않는 것 같아용.. 제 생각이지만;;
